name: release
on:  
  push:
    tags:
      - '*'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: echo "implement e2e tests"

  # push-image:
  #   needs: e2e
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: all

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

  #     - uses: docker/build-push-action@v2
  #       with:
  #         platforms: linux/amd64,linux/arm64,linux/arm/v7
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/findy-template-go:${{ env.version }}
  #           ghcr.io/${{ github.repository_owner }}/findy-template-go:latest
  #         cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-template-go:latest
  #         cache-to: type=inline

  merge:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: merge
        run:  |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master