name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: findy-network/setup-go-action@master
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt

  image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker image
        run: make dbuild
