name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: findy-network/setup-go-action@master
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          fail_ci_if_error: ${{ github.ref_name != 'dev' }}
          verbose: true

  image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker image
        run: make dbuild

  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          go-package: ./...
